---
title: "Project 2"
author: "Nicole Levin"
date: "2022-09-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Start playing around with functions and queries.
```{r}
#Maybe this code goes here?
rmarkdown::render(input = "Project2File.Rmd", 
                  output_format = "github_document", 
                  output_file = "README.md")

#Load libraries
library(httr)
library(dplyr)
library(jsonlite)
library(tidyverse)

```

Running some tests of how things work. This section won't go in our final file
```{r}
# #My API key c93de7d29d41461eac0f5e8272839b6e 
# 
# #Query for banana with 20 results
# food_test <- GET("https://api.spoonacular.com/recipes/findByIngredients?ingredients=banana&apiKey=c93de7d29d41461eac0f5e8272839b6e")
# parsed_food_test <- fromJSON(rawToChar(food_test$content))
# 
# #Grab what I care about
# food_test_results <- as_tibble(parsed_food_test) %>% select(title)
# 
# #Query based on nutrition
# food_test2 <- GET("https://api.spoonacular.com/recipes/findByNutrients?minCarbs=1&maxCarbs=50&number=20&apiKey=c93de7d29d41461eac0f5e8272839b6e")
# parsed_food_test2 <- fromJSON(rawToChar(food_test2$content))
# food_test2_results <- as_tibble(parsed_food_test2) %>% select(id, title, calories, protein, fat, carbs)
# 
# #Plot fat vs. calories
# g <- ggplot(data=food_test2_results, aes(x=calories, y=fat))
# g + geom_point()
# 
# #Plot carbs vs calories
# g <- ggplot(data=food_test2_results, aes(x=calories, y=carbs))
# g + geom_point()
# 
# #Plot protein vs calories
# g <- ggplot(data=food_test2_results, aes(x=calories, y=protein))
# g + geom_point()
# 
# #Plot carbs vs fat
# g <- ggplot(data=food_test2_results, aes(x=fat, y=carbs))
# g + geom_point()
# 
# #Create new variables, a carb/calories ratio and a macro-nutrient variable
# food_test2_results$protein <- extract_numeric(food_test2_results$protein)
# food_test2_results$carbs <- extract_numeric(food_test2_results$carbs)
# food_test2_results$fat <- extract_numeric(food_test2_results$fat)
# food_test2_results <- food_test2_results %>% mutate("ratio" = carbs/calories, "macros"= carbs + calories + protein)
# 
# #Cuisine search
# food_test3 <- GET("https://api.spoonacular.com/recipes/complexSearch?query=pasta&cuisine=italian&number=2&apiKey=c93de7d29d41461eac0f5e8272839b6e")
# parsed_food_test3 <- fromJSON(rawToChar(food_test3$content))
# food_test3_results <- parsed_food_test3$results
# 
# #Taking IDs found before, get some more info. My goal right now is to get a combination of numeric and categorical variables
# combo_search <- paste0("https://api.spoonacular.com/recipes/", food_test2_results$id[2], "/information?includeNutrition=false&apiKey=c93de7d29d41461eac0f5e8272839b6e")
# food_test4 <- GET(combo_search)
# parsed_food_test4 <- fromJSON(rawToChar(food_test4$content))
# food_test4_results <- c(parsed_food_test4$weightWatcherSmartPoints, parsed_food_test4$healthScore, parsed_food_test4$pricePerServing, parsed_food_test4$id, parsed_food_test4$title, parsed_food_test4$readyInMinutes)
# 
# #Try something similar, but with bulk. Can use this to get nutrition info, but the parsing might be hard.
# #Get list of IDs from a previous search
# id_list <- paste(as.character(food_test2_results$id[1:10]), collapse=",")
# bulk_search <- paste0("https://api.spoonacular.com/recipes/informationBulk?ids=", id_list, "&includeNutrition=false&apiKey=c93de7d29d41461eac0f5e8272839b6e")
# food_test5 <- GET(bulk_search)
# parsed_food_test5 <- fromJSON(rawToChar(food_test5$content))
# str(parsed_food_test5, levels=1)
# food_test5_results <- as_tibble(parsed_food_test5) %>% select(id, title, glutenFree, dairyFree, vegetarian, aggregateLikes, healthScore, weightWatcherSmartPoints, sourceName, pricePerServing, readyInMinutes)
# combined_results <- as_tibble(c(food_test5_results, food_test2_results[1:10,3:8]))
# combined_results <- combined_results %>% mutate(WW_category = if_else(weightWatcherSmartPoints <10, 1, if_else(weightWatcherSmartPoints <20, 2, 3))) 
# factor(combined_results$WW_category, levels = c(1, 2, 3), labels = c("low", "medium", "high"))
# combined_results <- combined_results %>% mutate(time_category = if_else(readyInMinutes <= 15, "quick", if_else(readyInMinutes <= 45, "medium", "long")))
# #My general thought is to use a nutrition or ingredient search to get a list of IDs to use for the rest of the searching and analysis. We can pull Weight Watchers points, price per serving, ready in minutes, health score, price per serving, ready in minutes, and aggregate likes as quantitative data. Potential options for some categorical stuff are vegetarian, gluten free, dairy free, source name. Can use cuisines, dish types, diets possibly, but those may be hard to parse.
# 
# #Can use the categorical data of gluten free, vegetarian, and dairy free for contingency tables
# #Can look at whether anything seems to correlate with aggregate likes: health score, price per serving, ready in minutes, calories.
# #Can create box plot based on whatever numeric thing we want, break out into vegetarian and not, gluten free and not, dairy free and not.
# #Break into categories and get summary statistics. Average health score for vegetarian, average fat for gluten free, etc.
# #Create categorical variable for ready in minutes. 0-15: quick, >15-45: average, >45: long
# #Create categorical WW Points: 0-10=low, >10-20=medium, >20=high
# 
# #One set of options to achieve minimum plot requirements: (1) Scatterplot of something vs aggregate likes or something vs health score, (2)box plots of health scores by vegetarian and not, (3) bar plot of categorized ready minutes or WW Points and pick a variable to group by like gluten free, (4) histogram of health score or calories, plus a 5th of some type.
# 
# #Plots for example. First, some scatterplot options.
# g <- ggplot(combined_results, aes(x=calories, y=healthScore))
# g + geom_point()
# 
# g <- ggplot(combined_results, aes(x=calories, y=aggregateLikes))
# g + geom_point()
# 
# #Next box plot of calories broken out by vegetarian and not
# g <- ggplot(combined_results, aes(x=vegetarian, y=calories))
# g + geom_boxplot()
# 
# #Next a bar plot.
# g <- ggplot(combined_results, aes(x=WW_category))
# g + geom_bar(aes(fill=vegetarian), position="dodge")
# 
# #Next a histogram
# g <- ggplot(combined_results, aes(x=calories))
# g + geom_histogram()
# 
# #Try a search with a bunch of options to see if it works.
# new_test2 <- GET("https://api.spoonacular.com/recipes/findByIngredients?ingredients=banana&findByNutrients?minCalories=500&maxCalories=1500&apiKey=c93de7d29d41461eac0f5e8272839b6e")
# 
# parsed_new_test2 <- fromJSON(rawToChar(new_test2$content))
# new_test_results2 <- as_tibble(parsed_new_test2) %>% select(id, title)


```

Now I want to create functions to run searches with some different options and get the data we want.
```{r}
#User options for search. Can input: (1)ingredient for search, (2)Number of results
ingredient_search <- function(ingredient, number=8){
  ingredient <- tolower(ingredient)
  search_url <- paste0("https://api.spoonacular.com/recipes/findByIngredients?ingredients=", ingredient,"&number=", number, "&apiKey=c93de7d29d41461eac0f5e8272839b6e")
  search_result <- GET(search_url)
  parsed_search_result <- fromJSON(rawToChar(search_result$content))
  id_list <- paste(as.character(parsed_search_result$id), collapse=",")
  bulk_url <- paste0("https://api.spoonacular.com/recipes/informationBulk?ids=", id_list, "&includeNutrition=false&apiKey=c93de7d29d41461eac0f5e8272839b6e")
  bulk_search <- GET(bulk_url)
  parsed_bulk_search <- fromJSON(rawToChar(bulk_search$content))
  results_df <- as_tibble(parsed_bulk_search) %>% select(id, title, glutenFree, dairyFree, vegetarian, aggregateLikes, healthScore, weightWatcherSmartPoints, sourceName, pricePerServing, readyInMinutes)
  combined_results <- results_df %>% mutate(WW_category = if_else(weightWatcherSmartPoints <10, 1, if_else(weightWatcherSmartPoints <20, 2, 3))) 
  factor(combined_results$WW_category, levels = c(1, 2, 3), labels = c("low", "medium", "high"))
return(combined_results)
}

#Run a test
ingredient_test <- ingredient_search("cherry", 32)

#This function is a search by calories. User options are (1)Minimum calories, (2)Maximum calories, (3)Whether we want a random set of results or the first ones alphabetically, and a number of results. All of these have defaults, so the user can specify nothing and still get a result.
calorie_search <- function(min_calories=0, max_calories=5000, random=FALSE, number=10){
  if(random==FALSE){
    search_url <- paste0("https://api.spoonacular.com/recipes/findByNutrients?minCalories=",min_calories,"&maxCalories=",max_calories,"&number=", number, "&apiKey=c93de7d29d41461eac0f5e8272839b6e")}
  else {search_url <- paste0("https://api.spoonacular.com/recipes/findByNutrients?minCalories=",min_calories,"&maxCalories=",max_calories,"&number=", number, "&random=true&apiKey=c93de7d29d41461eac0f5e8272839b6e")}
  search_result <- GET(search_url)
  parsed_search_result <- fromJSON(rawToChar(search_result$content))
  id_list <- paste(as.character(parsed_search_result$id), collapse=",")
  
  bulk_url <- paste0("https://api.spoonacular.com/recipes/informationBulk?ids=", id_list, "&includeNutrition=false&apiKey=c93de7d29d41461eac0f5e8272839b6e")
  bulk_search <- GET(bulk_url)
  parsed_bulk_search <- fromJSON(rawToChar(bulk_search$content))
  results_df <- as_tibble(parsed_bulk_search) %>% select(id, title, glutenFree, dairyFree, vegetarian, aggregateLikes, healthScore, weightWatcherSmartPoints, sourceName, pricePerServing, readyInMinutes)
  results_df <- results_df %>% mutate(WW_category = if_else(weightWatcherSmartPoints <10, 1, if_else(weightWatcherSmartPoints <20, 2, 3))) 
  factor(combined_results$WW_category, levels = c(1, 2, 3), labels = c("low", "medium", "high"))
  combined_results <- as_tibble(c(results_df, parsed_search_result[,3:8]))
  return(combined_results)
}

calorie_test <- calorie_search(min_calories = 100, max_calories = 500, number=30)

#Plot my test as a bar plot
g <- ggplot(calorie_test, aes(x=WW_category))
g + geom_bar(aes(fill=vegetarian), position="dodge")

g <- ggplot(ingredient_test, aes(x=WW_category))
g + geom_bar(aes(fill=vegetarian), position="dodge")

#Some scatterplot options.
g <- ggplot(calorie_test, aes(x=calories, y=healthScore))
g + geom_point()

g <- ggplot(ingredient_test, aes(x=weightWatcherSmartPoints, y=healthScore))
g + geom_point()

g <- ggplot(calorie_test, aes(x=calories, y=aggregateLikes))
g + geom_point()

g <- ggplot(ingredient_test, aes(x=healthScore, y=aggregateLikes))
g + geom_point()

#Next box plot of calories or health score broken out by vegetarian and not
g <- ggplot(calorie_test, aes(x=vegetarian, y=calories))
g + geom_boxplot()

g <- ggplot(ingredient_test, aes(x=vegetarian, y=healthScore))
g + geom_boxplot()

#Next some histograms
g <- ggplot(calorie_test, aes(x=calories))
g + geom_histogram(bins=10, color = "black", fill = "blue",
size = 2)

g <- ggplot(ingredient_test, aes(x=healthScore))
g + geom_histogram(bins=10, color = "black", fill = "blue",
size = 2)

#Create some contingency tables
table(ingredient_test$WW_category)
table(ingredient_test$WW_category, ingredient_test$vegetarian)
table(calorie_test$glutenFree, calorie_test$dairyFree)



```

